language: r
cache: packages
sudo: false

script:
  - Rscript -e 'devtools::check()'
  - Rscript -e 'devtools::document()'

after_success:  
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'rmarkdown::render("report/Report.Rmd")'
  - cp report/Report.pdf docs/examples/Report.pdf
  #- cp cname docs/CNAME 

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: docs
  on: 
    branch: master


