---
title: "Using the sendis package"
author: "F. Michel-Sendis"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette 
vignette: >
  %\VignetteIndexEntry{sendis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  message=FALSE, 
  warning=FALSE, 
  eval=TRUE,
  fig.align='center'
)

library(dplyr)

```
 
## Installation 

To use the `sendis` package you will need a working version of the [R software](https://www.r-project.org/). 

In an R console, load the necessary libraries: 

```{r, installation, warning=FALSE, message=FALSE, eval=TRUE}
# First time installation  
# If required, download the devtools package and load it :
if (system.file(package="devtools") == "") install.packages("devtools")
library(devtools)

# Install and load the latest development version from GitHub:
if (system.file(package="sendis") == "")  devtools::install_github("fmichelsendis/sendis")
library(sendis)
```

## Datasets

You now have a series of datasets available. Try exploring them : 

```{r, fig.show='hold'}
knitr::kable(head(calcs))
```
 

You can try to plot a pre-defined plot with one of the plot functions : 

```{r, fig.show='hold'}
df<-filter(sendis, INST=="NEA", VER!="2.2")
sendis::plot_cumulchi(df)
```
 
